### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ALFURRER** [deividAlfa/stm32_soldering_iron_controller#3] opened 2021-08-19 07:53 UTC
Hello, I am facing a problem. When trying to calibrate the soldering iron tip, this bug appears with the image! 
![1629359519871](https://user-images.githubusercontent.com/87298825/130029896-c9e2e70f-89d9-49ab-a8ab-614bb1bae7fb.jpg)
![1629359519870](https://user-images.githubusercontent.com/87298825/130029904-cc3f07c3-24a2-40ed-96ef-9c90ecd63037.jpg)

**Comment by ALFURRER** [comment] 2021-08-19 07:54
SW: 2021-08-18
HW:KSGER V3.x

**Comment by deividAlfa** [comment] 2021-08-19 10:41
Have you removed the screen at some moment?
That's usually caused when you change the screen and some connection gets damaged.
Did you modify the board in some way?
Nobody is having this issue, and the current oled code has been working perfectly for months.

**Comment by ALFURRER** [comment] 2021-08-19 10:50
No, I did not shoot the screen, there were no such problems on the previous firmware version from 08-10-2021. Yes, I changed the op amp to a precision one.
Again, this has not happened since the previous version of the firmware. And I didn't make a backup.

**Comment by ALFURRER** [comment] 2021-08-19 10:50
Again, this happens if I just turn the encoder knob in the main menu

**Comment by ALFURRER** [comment] 2021-08-19 10:53
![1629370344748](https://user-images.githubusercontent.com/87298825/130056779-4bec0d33-3ff1-4989-980e-20798436fab4.jpg)

**Comment by deividAlfa** [comment] 2021-08-19 11:26
Strange.
You can download any older version by checking the file history.
Click the 3 dots ...  view file. As far as I know no changes were made to the screen, but I'll check that again.
https://github.com/deividAlfa/stm32_soldering_iron_controller/commits/master/BOARDS/KSGER/%5Bv3%5D/STM32SolderingStation.bin

Ensure it's not happenning with older versions.
Sometimes the CS or DC pin is badly soldered, causing this problem when the screen is working at high speeds.
Please test and report the results, this could be a real issue or just a defective board.

**Comment by ALFURRER** [comment] 2021-08-19 11:28
Ok) thanks)))

**Comment by ALFURRER** [comment] 2021-08-19 11:33
I will definitely check and inform you

**Comment by ALFURRER** [comment] 2021-08-19 12:04
I have checked the old firmware version from 10-08-2021. Everything works, the soldering iron tip is calibrated.
Once there was a bug with the display. I think that this bug appears in the event that it is bad to clear the memory of the controller before flashing.
Now I will try to fill in the new firmware from 08-18-2021.
I will unsubscribe based on the results.
PS. Sorry, my English is very bad, I use a translator

**Comment by ALFURRER** [comment] 2021-08-19 12:14
Я прошил плату новой версией прошивки. Откалибровал жало паяльника. Все в норме. Больше багов с экраном не наблюдал.
Скорее всего, этот баг появляется при плохом стирании памяти контроллера перед заливкой новой версии прошивки. 
Благодарю вас за помощь и консультацию, прошу меня извинить за беспокойство

**Comment by ALFURRER** [comment] 2021-08-19 12:15
I have flashed the board with a new firmware version. I calibrated the soldering iron tip. Everything is okay. I did not see any more bugs with the screen.
Most likely, this bug appears when the controller memory is badly erased before uploading a new firmware version.
Thank you for your help and advice, I ask you to excuse me for worrying.

**Comment by deividAlfa** [comment] 2021-08-19 12:21
I doubt it was caused by that. The firmware checks the settings, all have its own checksum and internal version, and if the firmware uses a different settings version or detectes a wrong checksum it will wipe them and restore defaults.
 
Some time ago, I had this issue caused by a bad earth connection.
My board wasn't happy when joining Earth (AC Plug ground) and Gnd (Board negative) together, but also leaving them unconnected caused issues.
I don't have a good earth at home, so it caused interferences, touching anything caused strange behaviors, the controller crashed, the readings were crazy and also the screen failed some times.
Connnecting earth and gnd through a resistor (20K-100K) works nicely for me.
My quicko does this from factory, comes with a 100K resistor. It was just me wanting to join them together.

I'll wait a little more, if everything keeps going ok I'll close the issue.

**Comment by ALFURRER** [comment] 2021-08-19 12:32
I also do not have a normal grounding at home. But in any case, I'll see how it works in the future. If anything, I'll let you know. Thank you for your help

**Comment by deividAlfa** [comment] 2021-08-23 23:20
Closed

**Closed as completed by deividAlfa** 2021-08-23 23:20 UTC
